name: Publish SmartUI CLI packages

on:
  release:
     types: [published]

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/prod-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Publish Logger Package
        run: |
          ls -la
          cd packages/logger
          npm install
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish Logger Package
        run: |
          ls -la
          cd packages/logger
          npm install
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish Logger Package
        run: |
          ls -la
          cd packages/logger
          npm install
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}